name: Update Event Data in Firebase

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 00:00 UTC daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r event_scrape/requirements.txt

    - name: Execute event_scrape.py script
      run: python event_scrape/event_scrape.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "Update event data in Firebase" --allow-empty)
        git push
