name: Update Event Data in Firebase

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # install the required Python version
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f event_scrape/requirements.txt ]; then pip install -r event_scrape/requirements.txt; fi
        
      - name: execute py script # run file
        run: |
          python event_scrape/event_scrape.py
